/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#484849",
        "on-tertiary-fixed-variant": "#68186c",
        "on-tertiary": "#6a196d",
        "tertiary": "#ffa5fa",
        "on-surface": "#ffffff",
        "error-dim": "#d7383b",
        "on-primary-fixed-variant": "#00207d",
        "on-tertiary-container": "#5e0b62",
        "on-primary-fixed": "#000000",
        "error-container": "#9f0519",
        "tertiary-fixed-dim": "#e388e0",
        "inverse-surface": "#fcf8f9",
        "outline": "#767576",
        "surface-container": "#1a191b",
        "primary-fixed-dim": "#718bff",
        "primary-dim": "#3e65ff",
        "on-primary": "#002283",
        "tertiary-dim": "#e388e0",
        "secondary-fixed-dim": "#b8c0ff",
        "surface-dim": "#0e0e0f",
        "on-error-container": "#ffa8a3",
        "secondary-container": "#2c3ba1",
        "tertiary-fixed": "#f295ef",
        "inverse-primary": "#124af1",
        "on-secondary": "#000f6d",
        "surface-variant": "#262627",
        "tertiary-container": "#f295ef",
        "surface": "#0e0e0f",
        "primary-fixed": "#849aff",
        "on-primary-container": "#001967",
        "surface-container-low": "#131314",
        "on-secondary-fixed-variant": "#3746ac",
        "surface-container-high": "#201f21",
        "secondary": "#8796ff",
        "on-secondary-container": "#c8cdff",
        "secondary-fixed": "#caceff",
        "on-secondary-fixed": "#14258f",
        "primary": "#97a9ff",
        "on-tertiary-fixed": "#3b003f",
        "background": "#0e0e0f",
        "secondary-dim": "#8796ff",
        "on-error": "#490006",
        "surface-bright": "#2c2c2d",
        "primary-container": "#849aff",
        "on-surface-variant": "#adaaab",
        "error": "#ff716c",
        "on-background": "#ffffff",
        "surface-container-lowest": "#000000",
        "inverse-on-surface": "#565556",
        "surface-container-highest": "#262627",
        "surface-tint": "#97a9ff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #97a9ff 0%, #849aff 100%)',
        'gradient-accent':  'linear-gradient(135deg, #97a9ff 0%, #e388e0 100%)',
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.4s ease-out forwards',
        'scan':       'scanLine 3s linear infinite',
        'float':      'float 4s ease-in-out infinite',
      },
      transitionDuration: {
        '400': '400ms',
        '600': '600ms',
        '700': '700ms',
      },
    },
  },
  plugins: [],
}